### ISSUE TITLE
TemplateDefaultContent wrong endpoint

### ISSUE THREAD

**Issue by paluchmateusz** [charlesthk/python-mailchimp#101]
In class TemplateDefaultContent is used bad endpoint. I used 'reports' instead 'templates'.
When i call api i have error:

> INFO requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): us14.api.mailchimp.com
DEBUG requests.packages.urllib3.connectionpool "GET /3.0/reports/TEMPLATE_ID/default-content HTTP/1.1" 404 168
*** HTTPError: 404 Client Error: Not Found for url: https://us14.api.mailchimp.com/3.0/reports/TEMPLATE_ID/default-content

Where 'TEMPLATE_ID' is some id

**Comment by stephenross** [comment]
This has been merged with #108. It will be loaded to PyPi shortly (@charlesthk)

**Comment by charlesthk** [comment]
@stephenross , 2.0.7 is on PyPi, thanks.
