### ISSUE TITLE
Wrong path constructed at create email queue

### ISSUE THREAD

**Issue by austing** [charlesthk/python-mailchimp#102]
Hi!

Just noticed a bug on a feature that is probably used less often than the others. The code [here](https://github.com/charlesthk/python-mailchimp/blob/f113ccc6030aae28fbd9ed65d6472ff3fc001868/mailchimp3/entities/automationemailqueues.py#L54) appears to be copied from [here](https://github.com/charlesthk/python-mailchimp/blob/71fe2182fb318b1816a4069dd4ca05c524231e8c/mailchimp3/entities/automationactions.py#L36).

It seems to me that the line from automationemailqueues.py should read like this instead:
`
            url=self._build_path(workflow_id, 'emails', email_id, 'queue'),
`

**Comment by charlesthk** [comment]
Hi @austing , thanks for your issue. Your are totally right.

I have just fixed it.
