### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by MelvinDRM** [charlesthk/python-mailchimp#107]
Hello,

First of all, thanks for this library.

I think it would be of great value to add handling of errors, I haven't seen anything regarding them in your README. I was using your library in Django and when the endpoint returns with an error, Django explodes in the library instead of handling it. This means I never get the JSON of error, therefore I can never give a comprehensive message.

Here is my code example:

```from django import forms
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from mailchimp3 import MailChimp

client = MailChimp('user', '<api_key>')


class SubscribeForm(forms.Form):
    name = forms.CharField(
        label=_('Your name'),
        max_length=255,
        widget=forms.TextInput(
            attrs={
                'class': 'wrapper subscribe_form_input',
                'placeholder': _('Your name')
            }
        ),
        error_messages={
            'required': _('Please enter your name')
        }
    )
    last_name = forms.CharField(
        label=_('Your last name'),
        max_length=255,
        widget=forms.TextInput(
            attrs={
                'class': 'wrapper subscribe_form_input',
                'placeholder': _('Your last name')
            }
        ),
        error_messages={
            'required': _('Please enter your last name')
        }
    )
    email = forms.EmailField(
        label=_('Your email address'),
        max_length=255,
        widget=forms.TextInput(
            attrs={
                'class': 'wrapper subscribe_form_input',
                'placeholder': _('Your email address')
            }
        ),
        error_messages={
            'required': _('Please enter your email address'),
            'invalid': _('Please enter a valid email address')
        }
    )

    def clean(self):
        form_data = self.cleaned_data

        name = form_data.get('name', None)
        last_name = form_data.get('last_name', None)
        email = form_data.get('email', None)

        if name and last_name and email:
            try:
                subscription = client.lists.members.create(
                    '<list_id>', {
                        'email_address': form_data['email'],
                        'status': 'pending',
                        'merge_fields': {
                            'FNAME': form_data['name'],
                            'LNAME': form_data['last_name'],
                        },
                    }
                )
                print subscription
            except:
                raise ValidationError(_(
                    "An error has occurred. " +
                    "This might be caused because you already " +
                    "have subscribed to our newsletter. " +
                    "If that's not the case, please try again."
                ))
```

If the library handles the error and manages to pass the JSON of the error to the developer, we could use it to show in a better way the reasons of errors.

Thanks for your great work and I hope this is helpful.

**Comment by stephenross** [comment]
We already handle a large number of errors and return meaningful error messages in the form of python Exceptions. For your app, you will need to use try/except to handle the error states that occur. Most of these errors will be `ValueError`s or `KeyError`s when specific data is not passed but is required, or the data passed does not match the required structure. These exceptions are raised before communication with the MailChimp API takes place to prevent errors from the output of that endpoint, though the errors will be sequentially triggered and fail on the first error. If anything fails at the MailChimp side after our error checking, we usually raise an HTTPError using the `raise_for_status` method to catch HTTP errors. 

Take a look at the code and method declarations for the API itself to see how different statuses are handled by the different operations [here](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/mailchimpclient.py).

**Comment by idangoldman** [comment]
@stephenross I'm looking for a bit more details on the error.

This is what I'm trying to do with the help of the package:

```
from mailchimp3 import MailChimp

def mailchimp_subscribe( email, username, api_key, list_id ):
    client = MailChimp( username, api_key )

    try:
        payload = {
            'email_address': email,
            'status': 'subscribed'
        }

        client.lists.members.create( list_id, payload )
    except Exception as e:
        print e

    return True
```

and this is the error I'm getting:

```
400 Client Error: Bad Request for url: https://usX.api.mailchimp.com/3.0/lists/{list_id}/members
```

When I'm trying the same thing with CURL:

```
curl --request POST \
--url 'https://usX.api.mailchimp.com/3.0/lists/{list_id}/members' \
--user 'username:api_key' \
--header 'content-type: application/json' \
--data '{"email_address":"name@email.work","status":"subscribed"}' \
--include
```

 I'm getting an elaborate error message:

```
HTTP/1.1 400 Bad Request
Server: openresty
Content-Type: application/problem+json; charset=utf-8
Content-Length: 237
X-Request-Id: X
Link: <https://usX.api.mailchimp.com/schema/3.0/ProblemDetailDocument.json>; rel="describedBy"
Date: Wed, 22 Feb 2017 19:15:45 GMT
Connection: close
Set-Cookie: _AVESTA_ENVIRONMENT=prod; path=/

{
    "type": "http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/",
    "title": "Member Exists",
    "status": 400,
    "detail": "name@email.work is already a list member. Use PUT to insert or update list members.",
    "instance": ""
}%
```

How can I get the error's response body or how can I help to add this code to the package?

**Comment by richardmable** [comment]
Yes, +1 for this as well. Playing around with the Mailchimp API playground, you get more informative error messages than this library returns, which tends to be a generic 
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://usX.api.mailchimp.com/3.0/lists
```
if issues arise other than required information is missing. I've currently wrapped my requests in `try/except` blocks like so, and with some digging, you can get the error fields out (assuming it returns the errors):

```
try:
        resp_list_create = g.mailchimp.lists.create(data=mc_data)
except Exception as e:
     errors = json.loads(e.response.text).get('errors')[0]

```

But rather than have to do that, it seems like there should be a better way to get the errors and exceptions back to the user in a bit more digestible format. I've forked the repo and started playing around with some ideas...

**Comment by brondsem** [comment]
I have been using this for better errors:

    class MailchimpError(Exception):
        pass
    ...

    try:
        # use API here
    except HTTPError as e:
        if e.response.status_code == 400:
            json = e.response.json()
            raise MailchimpError(json.get('errors') or json.get('detail') or json)
        else:
            raise

**Comment by charlesthk** [comment]
Closing in favor or PR #138
