### ISSUE TITLE
How to create multiple subscribers in single request

### ISSUE THREAD

**Issue by goraniliev** [charlesthk/python-mailchimp#112]
I have a list of users (from my database) and want to insert them into Mailchimp list. Here is the code I initially used:

```
for user_data in data:
            response = client.lists.members.create(list_id, obj)
```

After the 10th request I get Bad Request Error without any specifics, but I guess I exceeded the limits. I am wondering how can this be done in singe batch request. I couldn't find some batch request example online. It would be great if you can provide one. I looked at the create function inside batches.py and here is the data parameter description:

  ```
 data = {
            "operations": array*
            [
                {
                    "method": string* (Must be one of "GET", "POST", "PUT", or "PATCH")
                    "path": string*,
                }
            ]
        }
```

I don't really understand how to build this path parameter, I tried in a couple of ways but none of them worked for me.

Thanks in advance!

**Comment by stripathi669** [comment]
@goraniliev  Did you find some documentation for this? If yes, please do share
