### ISSUE TITLE
Where is `member`?

### ISSUE THREAD

**Issue by nouney** [charlesthk/python-mailchimp#114]
Hi,

I upgraded `mailchimp3` and got the following error when trying to add a member to a list:

> AttributeError: 'MailChimp' object has no attribute 'member'

What happened?

**Comment by stephenross** [comment]
You will need to provide some context, what was the exact code you were using when trying to add a member to a list and how were you authenticating your MailChimp account? Please post snippets of both of those (with your credentials redacted)

**Comment by nouney** [comment]
Here's my code:

```
data = {
    'email_address': None,
    'status': 'subscribed',
    'interests': {},
    'merge_fields': {}
}

/* filling data, not important */

mc = MailChimp(current_app.config['MAILCHIMP_USER'], current_app.config['MAILCHIMP_API_SECRET'])
email_hash = hashlib.md5(data['email_address']).hexdigest()
mc.member.create_or_update(current_app.config['MAILCHIMP_LIST'], email_hash, data)
```

**Comment by stephenross** [comment]
Ok, I see what you are doing. We completely overhauled the structure of the API wrapper with the change from version 1 to 2, with all endpoints now being linked using the hierarchy provided by the API documentation. Take a quick look at the README files for a quick rundown on making sure you are connecting to the API correctly (I don't think we changed that) and specifically look at the [list members](https://github.com/charlesthk/python-mailchimp#list-members) section for info on where you will be able to create or update a member object on a list.

As a note, all of the functions that interact with members, which require a hash of the email address, will accept either in our endpoint and we will make sure that the address is transformed properly if a hash is not provided. You can manually run the transformation using the helper function `check_subscriber_hash`, which will return either the input if it matches the format of a proper hash, or check that the info provided was an email address and compute the hash of that. If you don't want to, we automatically run that transformation on anything passed in that must be a subscriber_hash.

**Comment by nouney** [comment]
Oh I see, I should've take a look first, stupid me...

Thanks a lot @stephenross!
