### ISSUE TITLE
client.lists.segments.create failing

### ISSUE THREAD

**Issue by jazzyeagle** [charlesthk/python-mailchimp#128]
I'm getting an HTTPError: 400 when attempting to create a new segment.  Here is the code I'm using (sorry the spacing didn't come over properly.  Not sure what I'm doing wrong, but using quotes to show the spacing more appropriately):

> def create_group(group_name):
>>    mc_create_response = client.lists.segments.all(tc_list_id)
>>   print(mc_create_response)
>>    mc_create_response = client.lists.segments.create(tc_list_id, data={ 'name' : group_name })
>>    print(mc_create_response)

For privacy purposes, I won't provide the JSON results of the first print.  Rest assured, I am getting the expected information back from the client.lists.segments.all call/print.  The tc_list_id is a global variable in this file identifying the client ID.

On the second call, however, I'm getting:
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    sync(e_sess_id, egroups, mcgroups)
  File "main.py", line 15, in sync
    mailchimp.create_group(egroup['name'])
  File "/share/programs/thorncreek/elexio-mailchimp/mailchimp.py", line 26, in create_group
    mc_create_response = client.lists.segments.create(tc_list_id, data={ 'name' : group_name })
  File "/usr/lib/python3.6/site-packages/mailchimp3/entities/listsegments.py", line 46, in create
    response = self._mc_client._post(url=self._build_path(list_id, 'segments'), data=data)
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 25, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 71, in _post
    r.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://us14.api.mailchimp.com/3.0/lists/7059fa318b/segments

It appears that the difference between the two functions, based on the MailChimp API docs, appears to be GET vs. POST, so there's an issue with the POST call.

Any help would be greatly appreciated.

Thanks!!

**Comment by jazzyeagle** [comment]
I did some additional digging and figured out what I was doing wrong.  Closing issue.  Sorry about that.

**Comment by chadsaun** [comment]
What were you doing wrong?  Maybe I'm doing the same thing
