### ISSUE TITLE
campaign.actions.schedule raises TypeError

### ISSUE THREAD

**Issue by Arany** [charlesthk/python-mailchimp#130]
At least under Python 3.5 (have not tested other versions), the ``schedule`` function raises a ``TypeError: utcoffset() takes exactly one argument (0 given)``

According to the documentation, and also in the ``pytz`` implementation of ``tzinfo`` (I have tested with ``timezone.utc`` and ``pytz.utc``, both raise that Error), the utcoffset function wants the datetime as a parameter:
https://docs.python.org/3.5/library/datetime.html#datetime.tzinfo.utcoffset

You should just use ``datetime.utcoffset()``:
https://docs.python.org/3.5/library/datetime.html#datetime.datetime.utcoffset

**Comment by Arany** [comment]
Ah, this might be fixed with PR #124

**Comment by stephenross** [comment]
I have merged 124, we should be able to update the version number and drop a new release on PyPi later today. I will let @charlesthk know when I do the version bump to fix this.

**Comment by stephenross** [comment]
@charlesthk I have updated master to 2.0.12 and added a note about the new features, please put it up on PyPi so that we can close this

**Comment by charlesthk** [comment]
Hi @stephenross, the updated version is on PyPi, sorry for the delay.
