### ISSUE TITLE
Update to include changelog items from 2017-02-23

### ISSUE THREAD

**Issue by stephenross** [charlesthk/python-mailchimp#132]
Add Batch Webhooks
Add Product Images under E-Commerce > Products
Add information about new query parameters for the GET request for lists
Add new Location report
Probably nothing to change for the new output data for the GET for list members

**Comment by freko247** [comment]
As I mentioned in #136, I am working on storing the notifications, here is my take on serializing data returned from the webhooks...

```
def serialize_mailchimp_notification(raw_notification, notification={}):
    # Notifications from mailchimp are posted in key/value format, that is flattened.
    # This function serializes the raw notification into a nested dictionary
    line_pattern = r'^\"(.+)\": +\"(.+)\"(| |,|, )$'
    raw_key_pattern = r'\[(\w+)\]'
    for line in raw_notification.split('\n'):
        print line
        raw_key, value, _ = re.search(line_pattern, line).groups()
        keys = re.findall(raw_key_pattern, raw_key)
        if len(keys) == 0:
            keys = [raw_key, ]
        element = notification
        for key_index, key in enumerate(keys[:-1]):
            # if key is digit, create nested dict if element doesn't exist
            if key.isdigit():
                try:
                    element = element[int(key)]
                except IndexError:
                    element.append({})
                    element = element[-1]
            # if key is string, remember to check if we need to create nested dict or list
            else:
                next_key = keys[key_index + 1]
                if next_key.isdigit():
                    element = element.setdefault(key, [])
                else:
                    element = element.setdefault(key, {})
        # If lowest level is list, key must be digit, so then just append value
        if isinstance(element, list):
            element.append(value)
        # If lowest level is dict, key must be string, so update dict with key/value
        else:
            element[keys[-1]] = value
    return notification

```

**Comment by saschwarz** [comment]
I'm interested in this project and glanced at this and I'd propose using a "sentinel" value in place of the mutable `notification={}` to avoid having `notification`'s key/values grow across function calls (http://python-guide-pt-br.readthedocs.io/en/latest/writing/gotchas/#mutable-default-arguments)
 e.g.
```
def serialize_mailchimp_notification(raw_notification, notification=None):
    notification = notification or {}
```
 
As an outsider to this project, an example `raw_notification` in the doc string would be helpful to understand the parsing.

**Comment by stephenross** [comment]
The items in the basic changelog are present in #138. For specific implementations of a serializer, please create a PR on the master branch after the 2.1.0 release, and I would suggest adding the serializer to the helper functions file on the off chance that they use a similar format elsewhere in the API in the future.
