### ISSUE TITLE
No support for Member Groups / Roles?

### ISSUE THREAD

**Issue by tufelkinder** [charlesthk/python-mailchimp#134]
Just getting started with this and it looks pretty amazing. Any idea if you'll support group/role membership in the future?

**Comment by stephenross** [comment]
Could you please elaborate on what you are asking about? Are you talking about supporting a specific endpoint that is not currently implemented? Please take a look at issue #120 if that is the case to make sure it is not one of the items that will be covered by that change. If it is something else, please link the relevant documentation bit, and if it is included in one of the changelog entries in the Mailchimp documentation, please let us know that as well.

**Comment by charlesthk** [comment]
No response, closing this issue.
