### ISSUE TITLE
Serializing webhook request body

### ISSUE THREAD

**Issue by freko247** [charlesthk/python-mailchimp#136]
I'm currently working on integrating MailChimp with an e-commerce platform. We want to log different notifications from MailChimp using the [Webhooks](https://developer.mailchimp.com/documentation/mailchimp/guides/about-webhooks/) they provide, starting of with [batch notifications](http://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-batch-operations/).

The Webhooks post data in key/value format, which isn't really useful. The format reminds me of some kind of flattened JSON, with array indexes as a part of the key.

> "data[_links][0][href]": "https://usX.api.mailchimp.com/3.0/batches"
"data[_links][0][method]": "GET"
"data[_links][0][rel]":  "parent"
"data[_links][0][schema]": "https://usX.api.mailchimp.com/schema/3.0/CollectionLinks/Batches.json"
"data[_links][0][targetSchema]": "https://usX.api.mailchimp.com/schema/3.0/Definitions/Batches/CollectionResponse.json"
"data[_links][1][href]": "https://usX.api.mailchimp.com/3.0/batches/1234ab56cd"
"data[_links][1][method]": "GET"
"data[_links][1][rel]":  "self"
"data[_links][1][targetSchema]": "https://usX.api.mailchimp.com/schema/3.0/Definitions/Batches/Response.json"
"data[_links][2][href]": "https://usX.api.mailchimp.com/3.0/batches/1234ab56cd"
"data[_links][2][method]": "DELETE"
"data[_links][2][rel]":  "delete"
"data[completed_at]":  "2017-02-10T14:44:22+00:00"
"data[errored_operations]":  "0"
"data[finished_operations]": "1"
"data[id]":  "1234ab56cd"
"data[response_body_url]": "https://mailchimp-api-batch.s3.amazonaws.com/1234ab56cd-response.tar.gz?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Expires=1486739377&Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D"
"data[status]":  "finished"
"data[submitted_at]":  "2017-02-10T14:44:14+00:00"
"data[total_operations]":  "1"
"fired_at":  "2017-02-10 14:59:37"
"type":  "batch_operation_completed"

I would like to serialize the data into JSON and thought I'd ask if anyone has done something similar or case I implement a serializer from scratch, would this be something that would be valuable to include in this project?

**Comment by stephenross** [comment]
I am currently working on implementing the Batch Webhooks endpoint as we have not yet added the features associated with the changelog from February. Please see issue #132 for further information about what is being added. At this time, there is no firm ETA, though I will try and get it cleared up as soon as possible.
