### ISSUE TITLE
E-commerce - get for product variant is not working

### ISSUE THREAD

**Issue by szewczykmira** [charlesthk/python-mailchimp#149]
When trying to get variant I get error:
 `405 Client Error: Method Not Allowed for url: https://us16.api.mailchimp.com/3.0/ecommerce/stores/store/products/1/variants/1`

I've checked and this is caused by sending `POST` instead of `GET`:
```python
return self._mc_client._post(
      url=self._build_path(store_id, 'products', product_id, 'variants', variant_id),
      **kwargs
)
```

Is that expected behaviour?

**Comment by stephenross** [comment]
Hello @szewczykmira that is an error. Looking at that endpoint, we also have an error with the `all()` endpoint for the same reason. I have patched this on the master branch, and it should be on PyPi in a bit.

@charlesthk, Please put 2.0.17 up on PyPi, thanks

**Comment by charlesthk** [comment]
Hi @stephenross, thanks, the release is on PyPi !

**Comment by szewczykmira** [comment]
@stephenross @charlesthk Thanks for quick reaction!
