### ISSUE TITLE
How can I create more than 1 member in a list in a for loop?

### ISSUE THREAD

**Issue by pablodlm** [charlesthk/python-mailchimp#156]
Im trying to create more than 1 member to a list but it tells me i cant. 

"Max retries exceeded with url"

Is there any solution to this?

**Comment by charlesthk** [comment]
Hi @pablodlm, you definitely can add multiple members to your list at one.

For that you need to use Batch Operation, [documented on Mailchimp](https://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-batch-operations/) 

Batch operations are supported in this library, as shown in [batches.py](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/entities/batches.py)

Let me know is this solves your problem.

**Comment by alxvallejo** [comment]
@charlesthk That batches.py link is a 404

**Comment by stephenross** [comment]
The endpoint name was changed and is now located at [batchoperations.py](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/entities/batchoperations.py)
