### ISSUE TITLE
Changelogs after 3/03/2017

### ISSUE THREAD

**Issue by stephenross** [charlesthk/python-mailchimp#158]
Update the app to include the changes listed in http://developer.mailchimp.com/documentation/mailchimp/guides/changelog/ after the 3/03/2017 batch. It appears that there are 3 sets with varying numbers of changes.

**Comment by krzysztofwolski** [comment]
Hello, do you have ETA on that? Can't start upgrading packages without changelog.

**Comment by stephenross** [comment]
I do not, though I can try and look at it before this weekend if I have time. If you would like to try working it and submit a PR that covers the changes (or multiple if you want to break up the changelog into each named section), we can look at that.

**Comment by lamar-frankie** [comment]
I'd like to claim this issue if you are not actively working on it @stephenross.

**Comment by stephenross** [comment]
Go ahead, I haven't had a chance to get started sadly, so getting it done by someone would be great.

**Comment by lamar-frankie** [comment]
Cool.
