### ISSUE TITLE
OAuth question

### ISSUE THREAD

**Issue by charlex** [charlesthk/python-mailchimp#159]
Forgive me if this isn't the proper forum for questions, but with mailchimp3's recent support for OAuth, I want to be sure I am using correctly. 

To initialize a connection with an OAuth access token, the `mc_api` can be anything, correct?

As in, `foobar` could be anything and this is expected to work:

```
    client = MailChimp(
        'foobar',
        access_token='my_valid_access_token',
    )
    client.root.get()
```

**Comment by stephenross** [comment]
As you can see [here](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/mailchimpclient.py#L70-L73), the mc_api is ignored if an access_token is provided, so you could instead just do the following to authenticate:

    client = MailChimp(access_token='my_valid_access_token')

**Comment by stephenross** [comment]
The init for the MailChimp client has been updated to provide a default value of None to `mc_api` as suggested.
