### ISSUE TITLE
campaigns.send() raise TypeError

### ISSUE THREAD

**Issue by talespadua** [charlesthk/python-mailchimp#16]
I am trying to send emails of a campaign trought `client.campaign.send(campaing_id="some_id")`, but it gives me the error `TypeError: request() got an unexpected keyword argument 'json'`

I am missing something or this is a bug?

**Comment by charlesthk** [comment]
Hi,
this seems to be an issue with python-requests, which version of python-requests are you using ? Before version 2.4.2, python-requests does not accept the json keyword argument.

**Comment by talespadua** [comment]
You are right, I was using older version of python-requests.
Fixed now. Thanks!
