### ISSUE TITLE
Please follow Semantic Versioning in the future

### ISSUE THREAD

**Issue by kirsle** [charlesthk/python-mailchimp#160]
https://semver.org/

Your recent update to version `2.1.0` breaks backwards compatibility by swapping the order of parameters to the constructor and raising an exception in existing code where no such exception was raised on `2.0.x` versions of the library.

Per the semantic versioning guidelines, the "1" in `2.1.0` should imply that _new features_ were added which are _backwards compatible_ to previous `2.x.x` releases. This breaking change _should_ cause the version number to be upgraded to `3.0.0` as the API is not backwards compatible to a prior `2.x.x` release such as `2.0.18`

**Comment by stephenross** [comment]
Sorry for the delay in responding and the issues with this update. Originally, I don't think the change was going to include that, but when it did, I forgot to increment the correct number. @charlesthk would you be ok with killing the 2.1.0 version on PyPi and uploading a 3.0.0 instead with appropriate changes?

**Comment by charlesthk** [comment]
Hi @stephenross, thanks, The v3.0.0 is live on PyPi.
I haven't deleted the v2.1.0 from PyPi to avoid current projects using it to break because of a missing version (which might resides in requirements.txt).
