### ISSUE TITLE
Documentation issue regarding offset and `get_all=True` behavior

### ISSUE THREAD

**Issue by mikezawitkowski** [charlesthk/python-mailchimp#161]
From the docs:
>For endpoints that allow the pagination parameters, the all() method has an additional boolean get_all argument that will loop through all records until the API no longer returns any to get all records without manually performing an additional query. By default, count is 10 and offset is 0 for all endpoints that support it. The get_all parameter on the all() method on any endpoint defaults to false, which follows the values that are provided in the call, and using get_all=True will ignore the provided count and offset to ensure that all records are returned.

However when I run this with log level to DEBUG I noticed this call:

`GET Request: https://us14.api.mailchimp.com/3.0/lists/<listid>/members?count=5000&offset=0`

It also takes a very long time to complete this request. It seems that the documentation is not correct or perhaps I've configured my settings to override the default behavior of fetching 10 records at a time...

**Comment by stephenross** [comment]
I will need to update the documentation for that section. The bit about count defaulting to 10 and offset defaulting to 0 is talking about the values if nothing is provided. The documentation is missing mention that get_all forces those values to change. We fetch 5000 records at a time to limit the number of calls to the service and hopefully prevent calls from hitting any limits that MailChimp places on accounts. It might be a useful enhancement to allow an option to configure the value used by the `_iterate` function to something other than 5000, but when a list can have 100,000 emails, performing that in 10,000 calls would be massive overkill.

**Comment by stephenross** [comment]
The README files have been updated to explain the functionality of `get_all` in more detail.
