### ISSUE TITLE
client.lists.merge_fields.delete doesn't convert merge_id to str

### ISSUE THREAD

**Issue by OleLaursen** [charlesthk/python-mailchimp#163]
merge_fields.delete tries to build a path without ensuring the the merge_id it gets is a string. But the merge_ids you get from Mailchimp are ints. Thus the following example bombs

  r = client.lists.merge_fields.all(list_id=list_id, get_all=True)
  f = r["merge_fields"][0]
  client.lists.merge_fields.delete(list_id=list_id, merge_id=f["merge_id"])

on this line

        return self._mc_client._delete(url=self._build_path(list_id, 'merge-fields', merge_id))

Perhaps it would be easier to fix _build_path in baseapi.py to run str on each args.

**Comment by charlesthk** [comment]
Hi @OleLaursen , thanks for reporting this issue, I have fixed it in v3.0.1.
