### ISSUE TITLE
Update release to resolve #159, #160, and #162

### ISSUE THREAD

**Issue by stephenross** [charlesthk/python-mailchimp#164]
@charlesthk Hello Charles

I have made a couple updates that don't really change much, but one of the biggest changes is the version bump to 3.0.0 and update of some of the documentation to reflect that per #160. I have also resolved an issue pointed out in the most recent response in #159 and updated our iterate helper for #162. If possible, please take down the 2.1.0 release as mentioned in the problems from issue #160 and rerelease as 3.0.0 with the current set of updates. I have also updated the PyPi version badges in the readme to check PyPi for the version number automatically, so we only need to update the alt text each time and not the actual image link.

Thanks
@stephenross

**Comment by charlesthk** [comment]
Thanks @stephenross for this work, the v3.0.0 is now on PyPi.
