### ISSUE TITLE
Bug with sending plain text test emails

### ISSUE THREAD

**Issue by campenr** [charlesthk/python-mailchimp#171]
According to the [MailChimp API documentation](https://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#action-post_campaigns_campaign_id_actions_test) the valid data attribute for `send_type` to allow sending of plain text test emails is `plaintext`, not `plain_text` as is currently implemented in this package. 

PR #170 address this issue.

**Comment by charlesthk** [comment]
Hi @campenr , thanks for this and your PR. It has been merged and publish on PyPi.
