### ISSUE TITLE
Unable to find link_id in a Click Details Report Members Query

### ISSUE THREAD

**Issue by sst390** [charlesthk/python-mailchimp#173]
Hi, I want the report of all members whose emails were bounced for a Campaign. For this I tried the below query : 
client.reports.click_details.members.all(campaign_id=' ', link_id=' ', get_all=False)
Please tell me where can I find the lilnk_id for a campaign and please explain what the field is actually referring to.
Thanks in advance.

**Comment by charlesthk** [comment]
Hi @sst390,

you have this [thread](https://stackoverflow.com/questions/33959652/finding-cleaned-bounced-email-addresses-for-a-mailchimp-campaign-or-list) on SO which explains how to get unsubscribed / bounced emails.

Basically, you can do

`client.lists.members.all(list_id, count=100, status='unsubscribed')`
`client.lists.members.all(list_id, count=100, status='cleaned')` 

Hope this helps.

**Comment by sst390** [comment]
Hi, I wanted to know if there is a way to check all the bounced/cleaned emails using a campaign_id. 
For eg : we are able to get the list all of all unsubscribed members for a "Campaign" using the below query : client.reports.unsubscribes.all(campaign_id='', get_all=False)

But there is no way to get just the bounced report of all members from a particular "Campaign" and not the list.
