### ISSUE TITLE
[Error] Get members list

### ISSUE THREAD

**Issue by vankk** [charlesthk/python-mailchimp#177]
Hello, I'm using `client.lists.members.get` inside a Loop that run over a large amount of an array.

After a few seconds I receive the following error:
```Traceback (most recent call last):
  File "list.py", line 29, in <module>
    list_id=list_id, subscriber_hash=email)
  File "/root/env/lib/python3.5/site-packages/mailchimp3/entities/listmembers.py", line 116, in get
    return self._mc_client._get(url=self._build_path(list_id, 'members', subscriber_hash), **queryparams)
  File "/root/env/lib/python3.5/site-packages/mailchimp3/mailchimpclient.py", line 30, in wrapper
    return fn(self, *args, **kwargs)
  File "/root/env/lib/python3.5/site-packages/mailchimp3/mailchimpclient.py", line 163, in _get
    raise MailChimpError(r.json())
mailchimp3.mailchimpclient.MailChimpError: {'instance': '52cef21d-9e03-457f-a61b-5e41d987c5c9', 'status': 404, 'type': 'http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/', 'detail': 'The requested resource could not be found.', 'title': 'Resource Not Found'}
```
The line 29 that is occuring the error is this one: _hasEmail = client.lists.members.get(list_id=list_id, subscriber_hash=email)_

The variable _list_id_ returns the list id on MailChimp, and the variable _email_ returns the user e-mail.

What I'm doing wrong?

Thanks.

Regards,
vankk.

**Comment by stephenross** [comment]
The error you are getting is normal. The error indicates that it is a 404 status, and the glossary provided in the error (http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/) indicates that whatever object you are requesting does not exist. You are either passing in an email or hash (we generate the hash if you provide the email) and the related member doesn't exist on the list.

You can update your code to be a try/except loop instead and make the `client.lists.members.get` call in the try, then set `hasEmail=True` after the call and if there is an exception, check it for status 404 and set `hasEmail=False` in that case, with the else on that check allowing the error to bubble up so you can perform further checks. Sample example below, though you may need to import the MailChimpError to allow it to be used in the exception as written.

```
try:
    client.lists.members.get(list_id=list_id, subscriber_hash=email)
    hasEmail=True
except MailChimpError as e:
    if e['status'] == 404:
        hasEmail=False
    else:
        raise e
```

**Comment by vankk** [comment]
@stephenross Thank your for your anwser, I didn't expected that. I was thinking that this function returns a boolean. I updated the code with the previous snippet that you send but the error still persist, the **MailChimpError is not defined**.

**Comment by stephenross** [comment]
Like I mentioned, you will need to import the exception. It can be imported from `mailchimp3.mailchimpclient.MailChimpError`
