### ISSUE TITLE
Adding Tags to lists.members

### ISSUE THREAD

**Issue by volksman** [charlesthk/python-mailchimp#178]
Was wondering if I'm missing something or if support will be added to allow for tags on list members as per:

https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/#create-post_lists_list_id_members_subscriber_hash_tags

**Comment by volksman** [comment]
Please see pr#179

**Comment by charlesthk** [comment]
Hi @volksman, thanks, your PR is merged and on PyPi !

**Comment by ZERO20** [comment]
Thanks for the PR, I liked the tags, could you update the documentation? regards

**Comment by charlesthk** [comment]
Hi @ZERO20 I updated the documentation with tags. Thanks.
