### ISSUE TITLE
Prevent fake emails

### ISSUE THREAD

**Issue by vankk** [charlesthk/python-mailchimp#183]
Hello, I'm facing a problem that I'm not sure how I can handle. I'm inserting new users to a list, but sometimes could return an email that is fake, and the API script stop running. I'm trying to prevent that with the code below, but it keep returning that error.
```python
try:
	client.lists.members.get(
		list_id=listId, subscriber_hash=hashEmail)
	hasEmail = True
except Exception as e:
	hasEmail = False
```

The error is detail is:
```
showpeta@yopmail.com looks fake or invalid, please enter a real email address.
```

I tried to use email_validator, but didn't worked.
```python
try:
	validate_email(email)  # validate and get info
except EmailNotValidError as e:
	hasEmail = False
```

**Comment by stephenross** [comment]
Could you please be more specific on what you mean by a fake email? Is this a message you are getting back from the API when you try and submit a new member? Additionally, for using the get endpoint for list.members, you can provide either a pre-computed hash, or the raw email address, in the `subscriber_hash` attribute as we compute the hash if it does not match a valid hash structure.

**Comment by vankk** [comment]
I'm inserting new members to a list and some emails can be fake, on this case, the application crashed instead of ignore this new email `showpeta@yopmail.com`, that doesn't exist.

Could you be more specify about pre-computed has? I'm setting up a hash for the email `hashlib.md5(email.encode('utf-8').lower()).hexdigest()`.

**Comment by stephenross** [comment]
The pre-computed hash that you are using looks correct, though you can also simply pass the email address directly to the subscriber_hash attribute when calling the API.

Mailchimp does not allow obviously fake email addresses and you will not be able to prevent that error, so you will need to submit real addresses, though you can catch the error and skip it as it will be an HTTPError with a 400 status code.
