### ISSUE TITLE
Suggestion - show how to add a user to a list towards the top of the README

### ISSUE THREAD

**Issue by aaugustin** [charlesthk/python-mailchimp#22]
I believe the following is a rather common use case:

- sign up for MailChimp
- create a list
- subscribe users to this list when they sign up

It takes a few minutes to figure out the solution:

```python
client = Mailchimp(...)
client.member.create('<list_id>', {
    'email_address': 'john.doe@example.com',
    'status': 'subscribed',
    'merge_fields': {
        'FNAME': 'John',
        'LNAME': 'Doe',
    },
})
```

The onboarding experience would be smoother if the README showed that example (or a similar one).

I hope this feedback helps!

**Comment by charlesthk** [comment]
Thanks for this one, you are right !
