### ISSUE TITLE
Add support for "Add or update a list member"

### ISSUE THREAD

**Issue by aaugustin** [charlesthk/python-mailchimp#24]
It's documented here:

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash

This operation looks quite convenient because it's idempotent: it allows you to put a user in a list safely, regardless of whether the user was already in that list.

The API could be:

    mailchimp.member.create_or_update(list_id, email, data)

The library would compute the hash per MailChimp's spec:

    subscriber_hash = hashlib.md5(email.lower().encode()).hexdigest()

**Comment by gonzalomcruz** [comment]
Hi @aaugustin, I have created a new pull request which adds support for "create_or_update". Please check it out and vote up it here: https://github.com/charlesthk/python-mailchimp/pull/31

Thanks!

**Comment by charlesthk** [comment]
Thanks for this PR, I have just merged it into the master !
