### ISSUE TITLE
Suggest using PUT instead of POST when creating list members

### ISSUE THREAD

**Issue by pcolmer** [charlesthk/python-mailchimp#26]
There is an issue with how MailChimp handles deletion of list members, in that they don't delete them from the list, they change the status to "". If you want to add that person back to the list, you have to use the PUT operation to update the list member (PATCH apparently doesn't work).

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#

Since the PUT operation allows add or update, it might make sense to use that consistently instead of POST for creating a list member?

**Comment by sumitkumar1209** [comment]
Issue #24 is similar to this problem and has been resolved in the latest pull

**Comment by charlesthk** [comment]
Ok, I just close the issue then
