### ISSUE TITLE
Package on Pypi for python 3

### ISSUE THREAD

**Issue by SandeR2012** [charlesthk/python-mailchimp#34]
last available package for python 3 is [https://pypi.python.org/pypi/mailchimp3/1.0.12](url),
following versions are only for python 2 or it was planned?

**Comment by charlesthk** [comment]
Hi,

I will port this package to python3 as soon as I can.

Thanks

**Comment by aaugustin** [comment]
Indeed, I just noticed that I was getting 1.0.12 instead of the latest version.

The library appears to be working just fine on Python 3. Are you aware of things that don't work?

I'm happy to work on a Python 3 port if that helps. I have some experience — I ported Django.

**Comment by aaugustin** [comment]
In order to release a Python 3-compatible wheel on PyPI, you have to create a `setup.cfg` file with the following contents:

```
[bdist_wheel]
universal = 1
```

Then `python setup.py bdist_wheel upload` does the right thing.

You could also upload a source distribution with `python setup.py sdist upload`. That will allow installation on Python 3.

Let me know if there's anything I can do to help.

**Comment by charlesthk** [comment]
Hi @aaugustin, thanks for your help, I really appreciate. I have done what you suggested.

How can I give you proper access to the repo so that you can help me port this to Python3 ?

Many thanks.

**Comment by aaugustin** [comment]
I can work in my fork and submit pull requests. That should be enough. I don't expect the port to require many changes.

If you want to give me access to this repo, you can go to Settings > Collaborators and add me there.

**Comment by charlesthk** [comment]
I have just invited you as a collaborators, feel free to submit a pull request.

**Comment by aaugustin** [comment]
There's now a wheel on PyPI that works on Python 3, as far as I can tell.

I'll follow up in another issue or PR if I have changes to suggest.
