### ISSUE TITLE
Only 10 records returned

### ISSUE THREAD

**Issue by andjelx** [charlesthk/python-mailchimp#36]
Is this a bug e.g.  client.campaign.all() returns only 10.
How to handle all of them?

**Comment by andjelx** [comment]
Am I correctly get that I need to invoke client.campaign.all(count=XXX) to get all elements?

**Comment by andybak** [comment]
Seems that way from playing with client.member.all

Would be useful to document this.

**Comment by andjelx** [comment]
I have made short pull request to really process all entities - https://github.com/charlesthk/python-mailchimp/pull/39

**Comment by charlesthk** [comment]
Thanks @andjelx I have merged your PR !
