### ISSUE TITLE
No mention of 'member' in readme

### ISSUE THREAD

**Issue by andybak** [charlesthk/python-mailchimp#37]
I had to look through the source. I had been assuming it was list.members or similar.

Also - as mentioned in #36 - a mention in the docs about 'count' and other kwargs would be useful.

**Comment by chrism2671** [comment]
Did you figure out how to get the members of a list?

**Comment by andybak** [comment]
I think this worked:

        client = MailChimp('', settings.MAILCHIMP_APIKEY)
        api_response = client.member.all(settings.MAILCHIMP_LIST_ID, count=99999)
        members = api_response['members']

**Comment by charlesthk** [comment]
Hi,

I have updated the readme to explain how to use query params.

Thanks
