### ISSUE TITLE
MailChimp 3.0 Batch Operations - not mentioned in documentation

### ISSUE THREAD

**Issue by lamc** [charlesthk/python-mailchimp#41]
Do you have any documentation on how to implement batch operations with your wrapper.

I'm trying to create (push) new members to an existing list.

```
client = MailChimp('wsjtest', '0c3c8df32f69c29f0d696200ddadccdb-us13')

user_list = [{'email_address': 'crystal.lam@dowjones.com', 'status':'subscribe'}, {'email_address': 'rahul.sen@dowjones.com', 'status':'subscribe'}, {'email_address': 'daniel.zhao@dowjones.com', 'status':'subscribe'}]

list_id = '15602234bb'
sample= {}
final_array = []

for user in user_list:

	sample['method'] = "PUT"
	sample['email_address'] = user['email_address']
	sample['path'] = "lists/257561/members"
	final_array.append(sample)
	
print final_array

client.member.create(list_id, {
		"operations": final_array})

```

Is it that the api call of .create is expecting just one data object and not an array of dictionaries, that have all my user data in dictionaries?

**Comment by stephenross** [comment]
There is no current documentation in the package on how to run batch operations. There is a method in the batches attribute of the MailChimp class that you can use to perform this, with some basic documentation in the docstring. You would use `client.batches.execute()` and pass in a dictionary of data as mentioned [here](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/entities/batches.py#L36-L45). The action matching names can be found [here](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/helpers.py#L4-L10).

I currently have a pull request in that overhauls some of this among other things, and would require that you manually convert the body to JSON, but would allow you to simply generate the data as defined in the [endpoint documentation](http://developer.mailchimp.com/documentation/mailchimp/reference/batches/#create-post_batches) and just send it.

**Comment by ucola** [comment]
would be nice if somebody can put a peace of code here on how they works?

**Comment by ucola** [comment]
Here you have an example how to subscribe a user over batch

`
batchdata = [{'action': 'create', 'entity_params': {'lists', '1234', 'members'}, 'data': {'email_address': 'test@test.com', 'status': 'subscribed', 'merge_fields': {'FNAME': 'name', 'LNAME': 'name'}}}]
result = client.batches.execute(batchdata)
print result['status']
`

**Comment by stephenross** [comment]
With the update to v2.0.0 through PR #45, the prep and execute methods have been removed, partly because of the poor documentation on those methods. You can find documentation on the expected data when creating a batch operation [here](http://developer.mailchimp.com/documentation/mailchimp/reference/batches/#create-post_batches), and as mentioned before, you will need to manually convert the body data to JSON before passing it into the batch operations endpoint. Please let us know if there are any issues with the functioning of the new endpoints.
