### ISSUE TITLE
Add versioning on github

### ISSUE THREAD

**Issue by sataloger** [charlesthk/python-mailchimp#42]
Now project has 1.0.21 version in `setup.py`, but 1.0.17 on pypi and it's not easy to track commit which corresponds to each version. Think that adding versioning tags on github will help with this and make source installation easier (e.q. `pip install -e git+git://github.com/charlesthk/python-mailchimp.git@1.0.20#egg=mailchimp3`)

**Comment by charlesthk** [comment]
I have just upload a new version to pypi !

Thanks
