### ISSUE TITLE
.all() does not function as expected for all entity types

### ISSUE THREAD

**Issue by stephenross** [charlesthk/python-mailchimp#43]
Some entities such as members truly return all entities when queried (thanks to issue #36 and the pull request there), but other entities such as lists still only pull the first 10 entities. If possible, please update all endpoints so that they use the same behavior in this regard. I will start working on a PR if I have time to resolve this, but I didn't see it mentioned that it was still an issue here.

**Comment by charlesthk** [comment]
Hi,

I have updated the readme to answer you question.

You just need to add proper queryparams in your function like:

```python
client.member.all('123456', count=50, offset=100)
```

Let me know if that is ok for you.

Thanks
