### ISSUE TITLE
Inconsistent error handling

### ISSUE THREAD

**Issue by OleLaursen** [charlesthk/python-mailchimp#46]
I got an HTTPError from a list.create (BTW why is this not lists.create?) with no explanation at all. Looking at the source, I can see that _post raises HTTPError(request=r) with r being the response and not the request (I suppose that's a bug). _get, _delete, and _patch/_put all do different things. This makes it really hard to code robustly against.

I don't know if some of this is due to MailChimp having an inconsistent API, but here are some suggestions:

- All methods examine the returned result consistently and raise an exception upon getting back a not-OK status

- The exception could inherit from requests.exceptions.RequestException with request and response being filled in, and message being the detail field from the JSON that MailChimp returns, if available

That way, as a user of the library it would be easy to get started and debug what's wrong, and also easy to add error handling later (just slap a try: ... except requests.exceptions.RequestException as e: around the call).

**Comment by zruu** [comment]
+1 I totally agree with Ole.

**Comment by charlesthk** [comment]
Thanks for this issue. I will have a look at it !

**Comment by charlesthk** [comment]
@OleLaursen we can do that : "All methods raise an exception upon getting back a not-OK status". Indeed, an OK status is when the response have a status code of 200 and when you create an object, the response status code is 201 (CREATED) so we don't want to raise an error.

What's needed, is a consistent error handling for python requests errors, and for mailchimp api errors. I suggest we use `raise_for_status` instead.

**Comment by charlesthk** [comment]
@OleLaursen, can you tell me if the commit I did answer your needs ?

**Comment by OleLaursen** [comment]
Yes, I think so. I've just updated my code and done a couple of tests and so far everything seems to be working fine. I'll open another issue if I find a problem. Thanks!
