### ISSUE TITLE
request.patch got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by PatrickWatzlawik** [charlesthk/python-mailchimp#51]
I'm trying to update the subscription status of a user with help of your nice little library and got into an issue:

```python
MailChimp('username', 'key')
	.member
	.update('listID', 'userHash', {'status': 'unsubscribed'})
```

which results in following traceback:
```
File "/usr/local/lib/python2.7/dist-packages/mailchimp3/entities/member.py", line 29, in update
    return self._mc_client._patch(url=self._build_path(list_id, 'members', member_id), data=data)
  File "/usr/local/lib/python2.7/dist-packages/mailchimp3/mailchimpclient.py", line 25, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mailchimp3/mailchimpclient.py", line 96, in _patch
    r = requests.patch(url, auth=self.auth, json=data)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in patch
    return request('patch', url,  data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```
Looking into Pythons requests `patch` method shows:

```
def patch(url, data=None, **kwargs):
    """Sends a PATCH request.

    :param url: URL for the new :class:`Request` object.
    :param data: (optional) Dictionary, bytes, or file-like object to send in the body of the :class:`Request`.
    :param \*\*kwargs: Optional arguments that ``request`` takes.
    :return: :class:`Response <Response>` object
    :rtype: requests.Response
    """

    return request('patch', url,  data=data, **kwargs)
```

I think when you change `requests.patch(url, auth=self.auth, json=data)` to `requests.patch(url, auth=self.auth, data=data)` everything should work.

Maybe I'm wrong and dont see my fault, but this seems obvious.

Greetings!

**Comment by charlesthk** [comment]
Hi !

It looks like your requests library is under 2.4.2 (do a  `pip freeze` to check).

As python-requests [documentation](http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests) 

> Instead of encoding the dict yourself, you can also pass it directly using the json parameter (added in version 2.4.2) and it will be encoded automatically:

Let me known !

**Comment by PatrickWatzlawik** [comment]
Hey Charles,

Thanks for your fast response. You're right, requests was at 2.2 and 2.11 ist the current version and everything works now!

Thanks again and sorry for any inconveniences :) Hope you're having a nice day!
