### ISSUE TITLE
Wrong Docs

### ISSUE THREAD

**Issue by raagin** [charlesthk/python-mailchimp#58]
if i use client.lists how it's described in readme. i have:
`AttributeError: 'MailChimp' object has no attribute 'lists'`

**Comment by stephenross** [comment]
Could you please specify exactly what you are trying to do and what line you are having an error with?

**Comment by charlesthk** [comment]
Maybe you were using the 1.0 version, we have just published the new version on PyPi.

Please consider doing a `pip install mailchimp3 --upgrade`

**Comment by raagin** [comment]
Yes, i tried "pip install mailchimp3 --upgrade", got the new version (2.0.0) and everything works as expected. Thanks!

**Comment by charlesthk** [comment]
Thanks, that is perfect then.
