### ISSUE TITLE
Changes in mailchimp API?

### ISSUE THREAD

**Issue by SavinaRoja** [charlesthk/python-mailchimp#59]
New to both the mailchimp API as well as `python-mailchimp`, but I did some investigation on an issue I am having that leads me to think that perhaps something has changed in the API that `python-mailchimp` wraps.

To start, I was getting an error trying to fetch the email addresses out of one of my mailchimp lists using one of the examples:

`data = client.lists.members.all('<my-list-id>', fields="members.email_address,members.id", get_all=True)`

with the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../mailchimp3/entities/listmembers.py", line 96, in all
    return self._iterate(url=self._build_path(list_id, 'members'), **queryparams)
  File "/.../mailchimp3/baseapi.py", line 46, in _iterate
    total = result['total_items']
KeyError: 'total_items'
```

This seemed plenty weird, so I read into the API ([see: _Read>Get information about members in a list_](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#)  and then decided to add `"total_items"`:

`res = client.lists.members.all('<my-list-id>', fields="members.email_address,members.id,total_items", get_all=True)`

This resolved the `KeyError`, but the behavior is still not as to be expected; with a list containing more than 100 members, the returned result only returns the last page of numbers. I believe the issue lies with `merge_two_dicts` in [helpers.py](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/helpers.py). The response JSON data is of the form: `{'total_items': N, 'members': [{'email_address': '<address@domain>', 'id': '<hash-string>'}, ]}`. The `merge_two_dicts` function does shallow copy that will simply overwrite the `'members'` key instead of append the lists. In other terms, this is the expected behavior of `dict.update`:

```
>>> a = {'key': [1, 2, 3]}
>>> a.update({'key': [4, 5, 6]})
>>> print(a)
{'key': [4, 5, 6]}
```

Is this is due to a change in the API, or am I missing something else? If due to an API change, I haven't yet learned enough of mailchimp's documentation to be sure how to adjust to `python-mailchimp` without potentially causing other troubles. I'll be looking into it and feedback on this would be great.

**Comment by stephenross** [comment]
Hello @SavinaRoja 

Thanks for pointing out that oversight, never did actually test the all using specific fields, I will update all of the `all()` methods to add that key if it is not in there so that the iterate does not fail, as for the helpers issue with the merge_dict, I will need to look into that a bit later and see what we can do to get it working. Neither of these is an issue with the API itself, they are just things that got missed when we updated to implement the remaining endpoints and add the `.all()` methods. If you have any suggestions, please let us know so that we can take a look, or if you have any other errors.

**Comment by SavinaRoja** [comment]
This might serve for the dictionary merging. I replaced `merge_two_dictionaries` with this exact code and the results were good.

```
def merge_two(x, y):
    """
    Merges two dictionaries, x and y. Same as `x.update(y)` except in the case where the values of
    x[key] and y[key] are both lists, in which case it joins the list values.

    Returns a copy of x, z, updated by y, where:
      z[key] = x[key] + y[key]
    """
    z = x.copy()
    for key, value in y.items():
        if isinstance(value, list) and isinstance(z.get(key, None), list):
            z[key] += value
        else:
            z[key] = value
    return z
```

The only issue was that there is a duplicate (redundant) call in the iteration in `BaseApi._iterate`. I adjusted it to the following and got results that looked good.

```
def _iterate(self, url, **kwargs):
        """
        ...
        """
        result = self._mc_client._get(url=url, offset=0, count=100, **kwargs)
        total = result['total_items']
        if total > 100:
            for offset in range(1, int(total / 100) +1):  #changed start value for range; only change 
                result = merge_two_dicts(result, self._mc_client._get(
                    url=url,
                    offset=int(offset*100),
                    count=100,
                    **kwargs
                ))
            return result
        else:
            return result
```

**Comment by stephenross** [comment]
Merged, closing issue
