### ISSUE TITLE
Exception.message doesn't exist on Python 3

### ISSUE THREAD

**Issue by aaugustin** [charlesthk/python-mailchimp#61]
The current implementation (perhaps since version 2?) uses liberally the following pattern:

```python
        try:
            test = data['client_secret']
        except KeyError as error:
            error.message += ' The authorized app must have a client_secret'
            raise
```

Unfortunately `error.message` was deprecated in Python 2.6 and removed in Python 3.

**Comment by SavinaRoja** [comment]
Good note, this would obfuscate troubleshooting in current versions.

The comparable way to do this in Python 3 would be:

```
try:
    test = data['client-secret']
except KeyError as e:
    raise KeyError(str(e) + ' The authorized app must have a client_secret')
```

http://stackoverflow.com/questions/6062576/adding-information-to-an-exception#tab-top has some information on supporting both the old and new patterns. Just using `six` would probably do.

However, it really looks like this pattern is being used as validation of dict input for JSON, in which case I think creating something along the lines of `ApiValidationError` would be in order to replace `KeyError`. A little googling turned up a couple libraries that could probably serve the need more concisely:
 * [jsonschema](https://github.com/Julian/jsonschema)
 * [voluptuous](https://github.com/alecthomas/voluptuous)
 * [validictory](https://github.com/jamesturk/validictory).

I haven't personally used any of those before.

**Comment by aaugustin** [comment]
Python 3 is murch more easy. You don't have anything special do to. Just write this and exception chaining will provide the correct information:

```python
try:
    test = data['client-secret']
except KeyError:
    raise KeyError('The authorized app must have a client_secret')
```

Of course any other exception type can be used and the original exception is preserved in all cases.

I think it's possible to emulate exception chaining on Python 2 but I'm not sure how. (Personally I'm no longer investing any effort towards Python 2 as it's nearing end-of-life quickly.)

**Comment by stephenross** [comment]
@aaugustin You are correct, the version 2 refactor added all those exceptions and I was unaware at the time that that format for adding information to exceptions had been deprecated.

@SavinaRoja I see that the link that you have provided does include information on using `six.reraise()` to allow for raising an exception in a manner that functions properly in both Python 2.x and 3.x

I have found that future includes `raise_with_traceback`, which can be used in both python 2 and 3 to get us where we want, so I will be updating all of the exceptions to use that to allow the library to live for those using the new hotness like @aaugustin, and those like me that are stuck in the dark ages of 2.x for a little while longer.

**Comment by stephenross** [comment]
Apparently the future that I found is not `__future__` but a PyPi package called future, however it does appear to be a clean way of making bridging the gap simple, so I would like feedback from some of the other collaborators on what you think of using that library inside of python-mailchimp, or if we should stick to using sys and six to handle the cross generational exception handling. Documentation for future, specifically the part about exceptions, can be found [here](http://python-future.org/compatible_idioms.html#raising-exceptions)

**Comment by aaugustin** [comment]
Django uses this pattern:

```python
            try:
                do_stuff()
            except Exception as msg:
                new_msg = 'Blabla, %s.' % msg
                six.reraise(Exception, Exception(new_msg), sys.exc_info()[2])
```

(but we're dropping it in a couple months, along with the rest of Python 2 backwards compatibility.)

**Comment by stephenross** [comment]
I can do that, though I am going to work to maintain the Python 2 backwards compatibility for the foreseeable future as the application I support at work that uses this library is currently written with 2 and will remain so for the foreseeable future for a while yet.

**Comment by aaugustin** [comment]
Of course, this isn't a problem :-) Hopefully you can do this refactoring in a reasonably automated way.

**Comment by stephenross** [comment]
@aaugustin Just to have another set of eyes on it, does that PR look good to you?

**Comment by aaugustin** [comment]
Yes I think that should work. Thanks.

**Comment by aaugustin** [comment]
Perhaps we should push a bugfix release with the various fixes we discussed over the last couple days?

**Comment by stephenross** [comment]
@aaugustin I agree, though I think we should wait until #56 is resolved. I am not that familiar with PyPi, but would we reversion (2.0.1), or would we simply replace what is currently available under 2.0.0?

**Comment by aaugustin** [comment]
You can't replace a release, you have to make a new release with a new number. 2.0.1 sounds fine in this case.

**Comment by stephenross** [comment]
I am adding a new issue related to that so that we can better track when to push the next release, since there are a couple issues open and after they are finished we should be good to go
