### ISSUE TITLE
`enabled=False` doesn't work for methods that access `response['id']`

### ISSUE THREAD

**Issue by aaugustin** [charlesthk/python-mailchimp#62]
Currently python-mailchimp contains code like this in various methods:

```python
class ListMembers(BaseApi):
    def create(self, list_id, data):
        # ...
        response = self._mc_client._post(url=self._build_path(list_id, 'members'), data=data)
        self.subscriber_hash = response['id']
        return response
```

Unfortunately, when `enabled=False`, this fails because `self._mc_client._post` returns `None`:
```
>       self.subscriber_hash = response['id']
E       TypeError: 'NoneType' object is not subscriptable
```

I think `self.subscriber_hash = response['id'] if response else None` would do the job.

@stephenross If you added this code in your recent refactor perhaps you have an opinion on this? Thanks!

**Comment by stephenross** [comment]
Check out PR #63 to see if that will fix the problem that you found and let me know.

**Comment by stephenross** [comment]
Merged
