### ISSUE TITLE
Schedule Campaign: Datetime is not JSON serializable

### ISSUE THREAD

**Issue by YuanZheCSYZ** [charlesthk/python-mailchimp#86]
Hi,

The schedule campaign interface seems not work quite happily with the datetime, as it throws below error
`TypeError: datetime.datetime(xxxxx) is not JSON serializable`

Indeed the datetime.datetime obj is not JSON serializable. I think may be cast it into string in the end will be better. Add below line to file entities/campaignactions.py line 102. I'm not quite sure what the '+00:00' means and I just follow the http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#action-post_campaigns_campaign_id_actions_schedule
`data['schedule_time'] = data['schedule_time'].strftime("%Y-%m-%dT%H:%M:00+00:00")`

Hope this can help.

**Comment by stephenross** [comment]
Thanks for pointing out the error, I have created a new branch that I would be happy to have you test. If you could use the issue-86 branch and verify that you are able to properly schedule a campaign with the changes it has, we will get it merged up and push a new release onto PyPi after.

**Comment by YuanZheCSYZ** [comment]
Sure I will take a look. Thanks!

**Comment by charlesthk** [comment]
@YuanZheCSYZ does the patch by @stephenross solved this issue ?

**Comment by stephenross** [comment]
@YuanZheCSYZ Can you verify that the patch corrects the issue that you were having?

**Comment by YuanZheCSYZ** [comment]
Oh sorry I was get distracted by some other work. I think there were still some issue with this one as well. I will have I go

**Comment by YuanZheCSYZ** [comment]
Yeah I just tested, and I think it's working, but somehow my test campaign just doesn't like to be scheduled via neither Python client nor command line. Either way I will receive a 406 error saying "This campaign cannot be scheduled: .". However I can definitely schedule through the web interface. 

Anyone has the similar issue?

**Comment by charlesthk** [comment]
@YuanZheCSYZ did you have a look at this thread on StackOverflow ? 
http://stackoverflow.com/questions/36053294/mailchimp-api-v3-0-campaign-schedule-error

**Comment by stephenross** [comment]
@YuanZheCSYZ did the article that @charlesthk linked to give you the answer to your issue? I believe that all of our creation functions require that you have the appropriate data points to be able to schedule a campaign when you create the campaign.

**Comment by stephenross** [comment]
As there has been no response in the last month, I am considering this issue resolved.

**Comment by hdl-tangier** [comment]
I am using the gibbon gem and have the same error "This campaign cannot be scheduled: ." Anyone could solve it?

[Issue on gibbon](https://github.com/amro/gibbon/issues/243)
