### ISSUE TITLE
Broken on windows because of path.join

### ISSUE THREAD

**Issue by bfritscher** [charlesthk/python-mailchimp#9]
os.path.join adds 'list\\123\\members' instead of 'list/123/members' on windows.

**Comment by albedoweb** [comment]
Also came across this
Better to use always "/"
In baseapi.py something like:
```
def _build_path(self, *args):
        return "/".join([self.endpoint,] + list(args))
```

**Comment by charlesthk** [comment]
That's a good solution ! Would you please consider making a pull request about this change ?
