### ISSUE TITLE
Provide tarball (tar.gz) in pip

### ISSUE THREAD

**Issue by juno-visualsquares** [charlesthk/python-mailchimp#90]
This provides some convenience for users so as not to introduce extra dependency on wheel in development

**Comment by stephenross** [comment]
@charlesthk Any chance we can do this?

**Comment by charlesthk** [comment]
@stephenross I will have a look at it !

**Comment by jakul** [comment]
+1

I'm unable to install this package as I have to use `python setup.py install`, and setuptools won't install wheels

**Comment by charlesthk** [comment]
@jakul @juno-visualsquares, I have published a new version to PyPi (2.0.9) with a tarball, could you please tell me if it is ok for you ?

**Comment by jakul** [comment]
Works perfectly for me. Thanks for sorting this @charlesthk

**Comment by charlesthk** [comment]
Ok perfect, I close the issue !
