### ISSUE TITLE
Ask for requests version > 2.4.2 in dependencies

### ISSUE THREAD

**Issue by mpachas** [charlesthk/python-mailchimp#94]
json doesn't work with less

**Comment by stephenross** [comment]
According to the README files, we do not support lower than 2.7.0 for the requests dependancy. Looking at the setup file, it looks like we don't specify a minimum version there, so I have created a pull request to fix that. Please let us know if there are any issues with that.

**Comment by mpachas** [comment]
Thanks, its ok 👌

**Comment by charlesthk** [comment]
Hi, we have updated `setup.py` to ensure that requests version is high enough !
